### ISSUE TITLE
error in import of limelight xml for tide-search CONGA results.

### ISSUE THREAD

**Issue by freejstone** [yeastrc/limelight-import-conga#1]
Hi Mike,

I have finally found some time to play around with Limelight. I should have tried it earlier, but a few things came up. I seem to have ran into an issue importing the limelight xml file:

> The Limelight Import has failed.
> 
> No Imported short description
> 
> Import Failure Message (truncated):
> 
> This is not a valid Limelight XML file.  The Limelight XML File has XML structure problems and failed to parse or an error was found during XSD validation.  Please update the program that generated the Limelight XML File or ensure that the correct version is being used.  Parse error message: javax.xml.bind.UnmarshalException
>  - with linked exception:
> [org.xml.sax.SAXParseException; lineNumber: 114368; columnNumber: 160; cvc-pattern-valid: Value 'MKIILFLALITLATCELYHYQECVRGTTVLLKEPCSSGTYEGNSPFHPLA
> 
> ** END Import Failure Message
> 
> Thank you
> 
> limelight

Attached is the related files:
[conga.log.txt](https://github.com/yeastrc/limelight-import-conga/files/10610601/conga.log.txt)
[conga.target.txt](https://github.com/yeastrc/limelight-import-conga/files/10610602/conga.target.txt)
[ISL_410545_Chlorocebus_BosTaurus_2020-05-04.fasta.txt](https://github.com/yeastrc/limelight-import-conga/files/10610603/ISL_410545_Chlorocebus_BosTaurus_2020-05-04.fasta.txt)
[conga.limelight.xml.txt](https://github.com/yeastrc/limelight-import-conga/files/10610605/conga.limelight.xml.txt)

As always your help is greatly appreciated!

Thanks,

Jack

**Comment by mriffle** [comment]
Hi Jack, it looks like the culprit was a trailing asterisk in at least one of the protein sequences. I've updated the converter to remove those trailing asterisks when reading in the FASTA. The latest release should solve this problem.

**Comment by freejstone** [comment]
Thanks Mike for your quick fix, very much appreciate it!
