### ISSUE TITLE
Adding localized peptides?

### ISSUE THREAD

**Issue by freejstone** [yeastrc/limelight-import-conga#2]
Hi Mike,

Hope you're well. I've recently added pyAscoring to help localize CONGA's discovered peptides. For now I can easily just replace this localized version in place of the original peptide and upload to limelight this way. I don't suppose it is possible to have both the localized peptide (it will have the column name `localized_peptide`) and the unlocalized peptide (with the original column name `peptide`) to appear in limelight?

Cheers,

Jack

**Comment by mriffle** [comment]
Hi Jack, I'll check the output of the  latest version of CONGA and get back to you.

**Comment by mriffle** [comment]
Jack, I ran the latest version in the GitHub repo but don't see a `localized_peptide` column. How do I generate data with that column?

**Comment by freejstone** [comment]
Thanks for the speedy reply! Apologies I should have clarified that I haven't updated the latest release of CONGA with this functionality yet. (I have in the latest commit). I am waiting on a couple of fixes that I made to the pyascore module to be approved via a pull request first.

What I should have asked is whether you think limelight accepting such a `localized_peptide` as well as the original `peptide` is feasible? However after further consideration, I am not sure what such a thing would look like in limelight anyway. It would need to select one for the visualization purposes, presumably the `localized_peptide` in which case I am not sure what value there is in having the `peptide` column. Perhaps all there needs is a toggle that only imports the `localized_peptide` if that column is present. Is this possible?

I suppose you also need a `modification_info` column that also includes the localized modification as well (which I still need to implement).

Sorry for wasting your time! I clearly needed to think more about what I was asking.

**Comment by mriffle** [comment]
Jack, I think anything we need to do is possible.  ;)  I just think it would be really helpful to see some example output for me to understand what's involved. It's not clear to me what you mean by `localized_peptide`--is that a peptide string with an indicator of the localization of the open mod mass?

**Comment by freejstone** [comment]
Yes that it is essentially correct, `localized_peptide` is the peptide string in `peptide` with the possible addition of an extra modification of one of the aa sites. The `modification_info` comprises of the modifications identified in the original peptide string in `peptide` and the possibly extra localized modification. I have attached an example output file. Thanks Mike!!

[Ecl_2023_0209_neo_pepsep_150um_15cm_1-9_60min_TRX-DDA-Hs27-Xray-Recovery-0Gy-T1-0h-Pool-FR0_214.target_mods.txt](https://github.com/yeastrc/limelight-import-conga/files/11301296/Ecl_2023_0209_neo_pepsep_150um_15cm_1-9_60min_TRX-DDA-Hs27-Xray-Recovery-0Gy-T1-0h-Pool-FR0_214.target_mods.txt)

**Comment by mriffle** [comment]
Thanks for the example, all is clear to me now. Limelight does support localized open mods and can make use of this information.

A few comments:

- It would be more useful to replace `localized_peptide` with `open_mod_localization` (or maybe `delta_mass_localization`) and just report the integer position of the localization (maybe with 0 for n-terminus, 1 for the first residue, peptide_length + 1 for c-terminus). And if this field is empty, then it wasn't localized. To use `localized_peptide` as it is now, I would need to parse that string to find which position has the localization then separately use the `delta_mass` column for the mass of the open mod and put it into the database. It would be easier and less error-prone to just report the localized position.
- Unrelated to open mod, but I think the precision in `modification_info` looks like it might be broken. I'm seeing values like `-3.817700000000059` for a mod mass, think it would be more useful to report `-3.8177`.

**Comment by freejstone** [comment]
* I have updated the `modification_info` column to include the additional open-mod localized modification, as well as the original ones found in the original `peptide`. The `localized_peptide` is really just cosmetic. Does this suffice instead of `open_mod_localization`? Or do you think I should have the open mod localization kept separate?
* Yes thanks for that, I will round them to something like 4dp.

**Comment by freejstone** [comment]
Update: I added the `open_mod_localization` column in the same format as `modification_info`. Mixing the two seemed problematic depending on what the user was interested in. Currently there is no distinction for n-terminus or c-terminus with `modification_info`. If you recall, the notation say for an n-terminus modification of mass1 and a modification of mass2 on the amino acid in the first position is `1[mass1,mass2]`. Should this be changed to 0[mass1]1[mass2]? Or should I keep it as is? Thanks! This is what an output looks like now:

[07March2022-Lumos-DDA-Whitson-lens-P-T94-FR3-01.mzML_narrow_open.target_mods.txt](https://github.com/yeastrc/limelight-import-conga/files/11315753/07March2022-Lumos-DDA-Whitson-lens-P-T94-FR3-01.mzML_narrow_open.target_mods.txt)

**Comment by mriffle** [comment]
I like the `open_mod_localization` column and that it is separate from the `modification_info` column--I was going to suggest this. Question: are all open mods now localized?  If not, how are they represented in this column?

As for n- and c-terminal mods--if you _can_ distinguish between them explicitly, I think that is easier for people to work with. In which case, using 0[mass1] and list it as a separate entry in the list of mods in `modification_info`.

**Comment by freejstone** [comment]
> are all open mods now localized? If not, how are they represented in this column?

- So for narrow-peptides, the value in the `localized_peptide` column will be the same as that in the `peptide` column. The `open_mod_localization` column is empty.
- For open-peptides, it will always have a distinct value in the `localized_peptide` column different from the `peptide` column. The specific localization is tested with a user-provided list of modifications that they hope to see _and_ the observed delta-mass. The best scoring localization out of the user-provided list and the observed delta-mass is reported.
- This means that for some open-peptides, even after localizing to the `localized_peptide`, the delta-mass may still not be zero.
- I have a column called `localized_better` which is a boolean that indicates whether the match to the `localized_peptide` was scored higher than without this localization step.
- So in summary to answer your question, all open-peptides have a localization stored in `localized_peptide` in string format, or in `open_mod_localization` as position[mass] format. The localization may or may not be exactly the delta-mass reported. I have a boolean indicating whether the match to `localized_peptide` is better than `peptide`.

Perhaps limelight can take up either `localized_peptide` if `localized_better` is True, else it sticks with `peptide`:
- If it takes up `localized_peptide`, it uses both the the `modification_info` and `open_mod_localization`. The `delta_mass` currently is not the difference between the `localized_peptide` mass and the spectrum mass (it is still the difference between the `peptide` mass and spectrum mass). Should I have a `localized_peptide_delta_mass` as well?
- If it takes up `peptide`, it uses the `modification_info` along with the `delta_mass` as it currently does.

>As for n- and c-terminal mods--if you can distinguish between them explicitly, I think that is easier for people to work with. In which case, using 0[mass1] and list it as a separate entry in the list of mods in modification_info.

Yes sure no problem, I can do that.

Please let me know if any of the above is unclear -- it was a bit of a word-vomit on my part but hopefully it is specific enough.

**Comment by freejstone** [comment]
Hi Mike, 

Thought I would update you that I am working on fixing up the `modification_info` column so that modifications on the n-terminal are given by the form `0[mass]` and modifications on the c terminal are given by the form `(n + 1)[mass]` as discussed. I know it is a while ago now, but do you think following the above discussion that limelight will be able to read this style of output from CONGA?

Cheers,

Jack

**Comment by mriffle** [comment]
Hi Jack, specifying n- and c-terminal mod positions that way definitely works for me. Do you have a version of CONGA I can run that is producing the latest output? I'll make the necessary updates to the CONGA Limelight XML converter.

**Comment by freejstone** [comment]
Hi Mike, just pushed the latest version of CONGA now. Please let me know if you have any trouble, thanks a lot!!

**Comment by mriffle** [comment]
Jack, I've updated the latest version of the converter to use .target_mods.txt and double checked that mods at positions 0 and n+1 are properly supported. I'll take a look at the localization when supplying a scan file next.

**Comment by mriffle** [comment]
I've reviewed the docs and generated some output, but just want to be sure I have things right:

- If the user supplies scan data an attempt will be made to localization the open mod mass.
- If the user supplies specific mods, an attempt will be made to localize that specific mod only if the delta mass is sufficiently close to the user supplied mass. Otherwise the delta mass is used for localization.
- If the delta mass was used for localization, the `dm_used` column will be `True`

I'm not sure what `localized_better` is. If this is False, does this mean the localized version of the peptide scores worse than the unlocalized version? If this is the case, should I even use the localized version when importing into Limelight?

Assuming the above is correct, I think I will set `delta_mass` to be equal to `delta_mass - localized mass` when bringing data into Limelight. In the case that `dm_used` is True, `delta_mass` will always be `0`. Otherwise, `delta_mass` will be the difference between the `delta_mass` and the user supplied mass and should be more indicative of error (as in the narrow data).

**Comment by freejstone** [comment]
> If the user supplies scan data an attempt will be made to localization the open mod mass.

Yep that's right.

> If the user supplies specific mods, an attempt will be made to localize that specific mod only if the delta mass is sufficiently close to the user supplied mass. Otherwise the delta mass is used for localization.

Exactly 

> If the delta mass was used for localization, the dm_used column will be True.

Correct.

> If this is False, does this mean the localized version of the peptide scores worse than the unlocalized version? If this is the case, should I even use the localized version when importing into Limelight?

You are correct here too. Yes I agree, I think it would be great if limelight was able to import the localized version if the localized version scored higher, and just the ordinary unlocalized version if it scored worse (so long as that is not too difficult).

> Assuming the above is correct, I think I will set delta_mass to be equal to delta_mass - localized mass when bringing data into Limelight. In the case that dm_used is True, delta_mass will always be 0. Otherwise, delta_mass will be the difference between the delta_mass and the user supplied mass and should be more indicative of error (as in the narrow data).

I think this is a great idea, and fully on board!!

**Comment by mriffle** [comment]
I've updated the latest release of the Limelight XML converter to support localized open modifications like we described above, should be good to go!

**Comment by freejstone** [comment]
Incredible! Thank you so much Mike for always being a tremendous help! Greatly appreciated :)

**Comment by mriffle** [comment]
> Incredible! Thank you so much Mike for always being a tremendous help! Greatly appreciated :)

My pleasure!
